# Diskritisasi data (Binning) menggunakan K-Means Clustering dan melakukan Klasifikasi dengan model Naive Bayas dan Pohon Keputusan pada data yang sudah Diskritisasi dan data yang belum Diskritisasi

## Melakukan Diskritisasi data menggunakan K-Means Clustering

### Mengganti Label Sepal Length menjadi Kategori dengan 4 Cluster

Import Library

In [249]:
%pip install scikit-learn


import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

Note: you may need to restart the kernel to use updated packages.


Mengambil Data IRIS

In [250]:
# Baca data
data = pd.read_csv("IRIS_Diskritisasi.csv")

print("Data IRIS")
print(data.head())

Data IRIS
   id  sepal_length  sepal_width  petal_length  petal_width        class
0   1           5.1          3.5           1.4          0.2  Iris-setosa
1   2           4.9          3.0           1.4          0.2  Iris-setosa
2   3           4.7          3.2           1.3          0.2  Iris-setosa
3   4           4.6          3.1           1.5          0.2  Iris-setosa
4   5           5.0          3.6           1.4          0.2  Iris-setosa


 Mengambil label Sepal Length

In [251]:
# Ambil hanya kolom sepal_length untuk clustering
X = data[['sepal_length']].values

print("\nData IRIS Sepal Length")
print(X)


Data IRIS Sepal Length
[[5.1]
 [4.9]
 [4.7]
 [4.6]
 [5. ]
 [5.4]
 [4.6]
 [5. ]
 [4.4]
 [4.9]
 [5.4]
 [4.8]
 [4.8]
 [4.3]
 [5.8]
 [5.7]
 [5.4]
 [5.1]
 [5.7]
 [5.1]
 [5.4]
 [5.1]
 [4.6]
 [5.1]
 [4.8]
 [5. ]
 [5. ]
 [5.2]
 [5.2]
 [4.7]
 [4.8]
 [5.4]
 [5.2]
 [5.5]
 [4.9]
 [5. ]
 [5.5]
 [4.9]
 [4.4]
 [5.1]
 [5. ]
 [4.5]
 [4.4]
 [5. ]
 [5.1]
 [4.8]
 [5.1]
 [4.6]
 [5.3]
 [5. ]
 [7. ]
 [6.4]
 [6.9]
 [5.5]
 [6.5]
 [5.7]
 [6.3]
 [4.9]
 [6.6]
 [5.2]
 [5. ]
 [5.9]
 [6. ]
 [6.1]
 [5.6]
 [6.7]
 [5.6]
 [5.8]
 [6.2]
 [5.6]
 [5.9]
 [6.1]
 [6.3]
 [6.1]
 [6.4]
 [6.6]
 [6.8]
 [6.7]
 [6. ]
 [5.7]
 [5.5]
 [5.5]
 [5.8]
 [6. ]
 [5.4]
 [6. ]
 [6.7]
 [6.3]
 [5.6]
 [5.5]
 [5.5]
 [6.1]
 [5.8]
 [5. ]
 [5.6]
 [5.7]
 [5.7]
 [6.2]
 [5.1]
 [5.7]
 [6.3]
 [5.8]
 [7.1]
 [6.3]
 [6.5]
 [7.6]
 [4.9]
 [7.3]
 [6.7]
 [7.2]
 [6.5]
 [6.4]
 [6.8]
 [5.7]
 [5.8]
 [6.4]
 [6.5]
 [7.7]
 [7.7]
 [6. ]
 [6.9]
 [5.6]
 [7.7]
 [6.3]
 [6.7]
 [7.2]
 [6.2]
 [6.1]
 [6.4]
 [7.2]
 [7.4]
 [7.9]
 [6.4]
 [6.3]
 [6.1]
 [7.7]
 [6.3]
 [6.4]
 [6. ]
 [6

 Melakukan Normalisasi Data

In [252]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Sepal Length")
print(X_scaled)


Normalisasi data Sepal Length
[[-0.90068117]
 [-1.14301691]
 [-1.38535265]
 [-1.50652052]
 [-1.02184904]
 [-0.53717756]
 [-1.50652052]
 [-1.02184904]
 [-1.74885626]
 [-1.14301691]
 [-0.53717756]
 [-1.26418478]
 [-1.26418478]
 [-1.87002413]
 [-0.05250608]
 [-0.17367395]
 [-0.53717756]
 [-0.90068117]
 [-0.17367395]
 [-0.90068117]
 [-0.53717756]
 [-0.90068117]
 [-1.50652052]
 [-0.90068117]
 [-1.26418478]
 [-1.02184904]
 [-1.02184904]
 [-0.7795133 ]
 [-0.7795133 ]
 [-1.38535265]
 [-1.26418478]
 [-0.53717756]
 [-0.7795133 ]
 [-0.41600969]
 [-1.14301691]
 [-1.02184904]
 [-0.41600969]
 [-1.14301691]
 [-1.74885626]
 [-0.90068117]
 [-1.02184904]
 [-1.62768839]
 [-1.74885626]
 [-1.02184904]
 [-0.90068117]
 [-1.26418478]
 [-0.90068117]
 [-1.50652052]
 [-0.65834543]
 [-1.02184904]
 [ 1.40150837]
 [ 0.67450115]
 [ 1.2803405 ]
 [-0.41600969]
 [ 0.79566902]
 [-0.17367395]
 [ 0.55333328]
 [-1.14301691]
 [ 0.91683689]
 [-0.7795133 ]
 [-1.02184904]
 [ 0.06866179]
 [ 0.18982966]
 [ 0.31099753]
 [-0.2948

 Melakukan Clustering dengan 4 Cluster

In [253]:
# Clustering
kms = KMeans(n_clusters=4, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[2 2 2 2 2 0 2 2 2 2 0 2 2 2 0 0 0 2 0 2 0 2 2 2 2 2 2 2 2 2 2 0 2 0 2 2 0
 2 2 2 2 2 2 2 2 2 2 2 0 2 1 3 1 0 3 0 3 2 3 2 2 0 0 3 0 3 0 0 3 0 0 3 3 3
 3 3 3 3 0 0 0 0 0 0 0 0 3 3 0 0 0 3 0 2 0 0 0 3 2 0 3 0 1 3 3 1 2 1 3 1 3
 3 3 0 0 3 3 1 1 0 1 0 1 3 3 1 3 3 3 1 1 1 3 3 3 1 3 3 0 1 3 1 0 3 3 3 3 3
 3 0]


 Mengubah Label Cluster menjadi angka

In [254]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['C' 'C' 'C' 'C' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'C' 'C' 'C' 'A' 'A' 'A' 'C'
 'A' 'C' 'A' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'A' 'C' 'A' 'C' 'C'
 'A' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'A' 'C' 'B' 'D' 'B' 'A'
 'D' 'A' 'D' 'C' 'D' 'C' 'C' 'A' 'A' 'D' 'A' 'D' 'A' 'A' 'D' 'A' 'A' 'D'
 'D' 'D' 'D' 'D' 'D' 'D' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'D' 'D' 'A' 'A'
 'A' 'D' 'A' 'C' 'A' 'A' 'A' 'D' 'C' 'A' 'D' 'A' 'B' 'D' 'D' 'B' 'C' 'B'
 'D' 'B' 'D' 'D' 'D' 'A' 'A' 'D' 'D' 'B' 'B' 'A' 'B' 'A' 'B' 'D' 'D' 'B'
 'D' 'D' 'D' 'B' 'B' 'B' 'D' 'D' 'D' 'B' 'D' 'D' 'A' 'B' 'D' 'B' 'A' 'D'
 'D' 'D' 'D' 'D' 'D' 'A']


 Mengubah Data Sepal Length menjadi Cluster yang telah dilakukan sebelumnya dan disimpan ke CSV

In [255]:
# Ganti kolom sepal_length dengan label huruf cluster
data['sepal_length'] = cluster_labels_named_np
print("\nData IRIS dengan 'sepal_length' diganti huruf cluster:")
print(data)

# Simpan ke CSV
data.to_csv("IRIS_Diskritisasi.csv", index=False)


Data IRIS dengan 'sepal_length' diganti huruf cluster:
      id sepal_length  sepal_width  petal_length  petal_width           class
0      1            C          3.5           1.4          0.2     Iris-setosa
1      2            C          3.0           1.4          0.2     Iris-setosa
2      3            C          3.2           1.3          0.2     Iris-setosa
3      4            C          3.1           1.5          0.2     Iris-setosa
4      5            C          3.6           1.4          0.2     Iris-setosa
..   ...          ...          ...           ...          ...             ...
145  146            D          3.0           5.2          2.3  Iris-virginica
146  147            D          2.5           5.0          1.9  Iris-virginica
147  148            D          3.0           5.2          2.0  Iris-virginica
148  149            D          3.4           5.4          2.3  Iris-virginica
149  150            A          3.0           5.1          1.8  Iris-virginica

[150 ro

### Mengganti Label Sepal Width menjadi Kategori dengan 3 Cluster

 Mengambil Data IRIS

In [256]:
# Baca data
data = pd.read_csv("IRIS_Diskritisasi.csv")

print("Data IRIS")
print(data.head())

Data IRIS
   id sepal_length  sepal_width  petal_length  petal_width        class
0   1            C          3.5           1.4          0.2  Iris-setosa
1   2            C          3.0           1.4          0.2  Iris-setosa
2   3            C          3.2           1.3          0.2  Iris-setosa
3   4            C          3.1           1.5          0.2  Iris-setosa
4   5            C          3.6           1.4          0.2  Iris-setosa


 Mengambil label Sepal Width

In [257]:
# Ambil hanya kolom sepal_width untuk clustering
X = data[['sepal_width']].values

print("\nData IRIS Sepal Width")
print(X)


Data IRIS Sepal Width
[[3.5]
 [3. ]
 [3.2]
 [3.1]
 [3.6]
 [3.9]
 [3.4]
 [3.4]
 [2.9]
 [3.1]
 [3.7]
 [3.4]
 [3. ]
 [3. ]
 [4. ]
 [4.4]
 [3.9]
 [3.5]
 [3.8]
 [3.8]
 [3.4]
 [3.7]
 [3.6]
 [3.3]
 [3.4]
 [3. ]
 [3.4]
 [3.5]
 [3.4]
 [3.2]
 [3.1]
 [3.4]
 [4.1]
 [4.2]
 [3.1]
 [3.2]
 [3.5]
 [3.1]
 [3. ]
 [3.4]
 [3.5]
 [2.3]
 [3.2]
 [3.5]
 [3.8]
 [3. ]
 [3.8]
 [3.2]
 [3.7]
 [3.3]
 [3.2]
 [3.2]
 [3.1]
 [2.3]
 [2.8]
 [2.8]
 [3.3]
 [2.4]
 [2.9]
 [2.7]
 [2. ]
 [3. ]
 [2.2]
 [2.9]
 [2.9]
 [3.1]
 [3. ]
 [2.7]
 [2.2]
 [2.5]
 [3.2]
 [2.8]
 [2.5]
 [2.8]
 [2.9]
 [3. ]
 [2.8]
 [3. ]
 [2.9]
 [2.6]
 [2.4]
 [2.4]
 [2.7]
 [2.7]
 [3. ]
 [3.4]
 [3.1]
 [2.3]
 [3. ]
 [2.5]
 [2.6]
 [3. ]
 [2.6]
 [2.3]
 [2.7]
 [3. ]
 [2.9]
 [2.9]
 [2.5]
 [2.8]
 [3.3]
 [2.7]
 [3. ]
 [2.9]
 [3. ]
 [3. ]
 [2.5]
 [2.9]
 [2.5]
 [3.6]
 [3.2]
 [2.7]
 [3. ]
 [2.5]
 [2.8]
 [3.2]
 [3. ]
 [3.8]
 [2.6]
 [2.2]
 [3.2]
 [2.8]
 [2.8]
 [2.7]
 [3.3]
 [3.2]
 [2.8]
 [3. ]
 [2.8]
 [3. ]
 [2.8]
 [3.8]
 [2.8]
 [2.8]
 [2.6]
 [3. ]
 [3.4]
 [3.1]
 [3. ]
 [3.

 Melakukan Normalisasi Data

In [258]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Sepal Width")
print(X_scaled)


Normalisasi data Sepal Width
[[ 1.03205722]
 [-0.1249576 ]
 [ 0.33784833]
 [ 0.10644536]
 [ 1.26346019]
 [ 1.95766909]
 [ 0.80065426]
 [ 0.80065426]
 [-0.35636057]
 [ 0.10644536]
 [ 1.49486315]
 [ 0.80065426]
 [-0.1249576 ]
 [-0.1249576 ]
 [ 2.18907205]
 [ 3.11468391]
 [ 1.95766909]
 [ 1.03205722]
 [ 1.72626612]
 [ 1.72626612]
 [ 0.80065426]
 [ 1.49486315]
 [ 1.26346019]
 [ 0.56925129]
 [ 0.80065426]
 [-0.1249576 ]
 [ 0.80065426]
 [ 1.03205722]
 [ 0.80065426]
 [ 0.33784833]
 [ 0.10644536]
 [ 0.80065426]
 [ 2.42047502]
 [ 2.65187798]
 [ 0.10644536]
 [ 0.33784833]
 [ 1.03205722]
 [ 0.10644536]
 [-0.1249576 ]
 [ 0.80065426]
 [ 1.03205722]
 [-1.74477836]
 [ 0.33784833]
 [ 1.03205722]
 [ 1.72626612]
 [-0.1249576 ]
 [ 1.72626612]
 [ 0.33784833]
 [ 1.49486315]
 [ 0.56925129]
 [ 0.33784833]
 [ 0.33784833]
 [ 0.10644536]
 [-1.74477836]
 [-0.58776353]
 [-0.58776353]
 [ 0.56925129]
 [-1.51337539]
 [-0.35636057]
 [-0.8191665 ]
 [-2.43898725]
 [-0.1249576 ]
 [-1.97618132]
 [-0.35636057]
 [-0.35636

 Melakukan Clustering dengan 3 Cluster

In [259]:
# Clustering
kms = KMeans(n_clusters=3, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[1 2 2 2 1 1 1 1 2 2 1 1 2 2 1 1 1 1 1 1 1 1 1 2 1 2 1 1 1 2 2 1 1 1 2 2 1
 2 2 1 1 0 2 1 1 2 1 2 1 2 2 2 2 0 0 0 2 0 2 0 0 2 0 2 2 2 2 0 0 0 2 0 0 0
 2 2 0 2 2 0 0 0 0 0 2 1 2 0 2 0 0 2 0 0 0 2 2 2 0 0 2 0 2 2 2 2 0 2 0 1 2
 0 2 0 0 2 2 1 0 0 2 0 0 0 2 2 0 2 0 2 0 1 0 0 0 2 1 2 2 2 2 2 0 2 2 2 0 2
 1 2]


 Mengubah Label Cluster menjadi angka

In [260]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['B' 'C' 'C' 'C' 'B' 'B' 'B' 'B' 'C' 'C' 'B' 'B' 'C' 'C' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'C' 'B' 'C' 'B' 'B' 'B' 'C' 'C' 'B' 'B' 'B' 'C' 'C'
 'B' 'C' 'C' 'B' 'B' 'A' 'C' 'B' 'B' 'C' 'B' 'C' 'B' 'C' 'C' 'C' 'C' 'A'
 'A' 'A' 'C' 'A' 'C' 'A' 'A' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'A' 'A' 'C' 'A'
 'A' 'A' 'C' 'C' 'A' 'C' 'C' 'A' 'A' 'A' 'A' 'A' 'C' 'B' 'C' 'A' 'C' 'A'
 'A' 'C' 'A' 'A' 'A' 'C' 'C' 'C' 'A' 'A' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'C'
 'A' 'B' 'C' 'A' 'C' 'A' 'A' 'C' 'C' 'B' 'A' 'A' 'C' 'A' 'A' 'A' 'C' 'C'
 'A' 'C' 'A' 'C' 'A' 'B' 'A' 'A' 'A' 'C' 'B' 'C' 'C' 'C' 'C' 'C' 'A' 'C'
 'C' 'C' 'A' 'C' 'B' 'C']


 Mengubah Data Sepal Width menjadi Cluster yang telah dilakukan sebelumnya dan disimpan ke CSV

In [261]:
# Ganti kolom sepal_width dengan label huruf cluster
data['sepal_width'] = cluster_labels_named_np
print("\nData IRIS dengan 'sepal_width' diganti huruf cluster:")
print(data)

# Simpan ke CSV
data.to_csv("IRIS_Diskritisasi.csv", index=False)


Data IRIS dengan 'sepal_width' diganti huruf cluster:
      id sepal_length sepal_width  petal_length  petal_width           class
0      1            C           B           1.4          0.2     Iris-setosa
1      2            C           C           1.4          0.2     Iris-setosa
2      3            C           C           1.3          0.2     Iris-setosa
3      4            C           C           1.5          0.2     Iris-setosa
4      5            C           B           1.4          0.2     Iris-setosa
..   ...          ...         ...           ...          ...             ...
145  146            D           C           5.2          2.3  Iris-virginica
146  147            D           A           5.0          1.9  Iris-virginica
147  148            D           C           5.2          2.0  Iris-virginica
148  149            D           B           5.4          2.3  Iris-virginica
149  150            A           C           5.1          1.8  Iris-virginica

[150 rows x 6 column

### Mengganti Label Petal Length menjadi Kategori dengan 4 Cluster

 Mengambil Data IRIS

In [262]:
# Baca data
data = pd.read_csv("IRIS_Diskritisasi.csv")

print("Data IRIS")
print(data.head())

Data IRIS
   id sepal_length sepal_width  petal_length  petal_width        class
0   1            C           B           1.4          0.2  Iris-setosa
1   2            C           C           1.4          0.2  Iris-setosa
2   3            C           C           1.3          0.2  Iris-setosa
3   4            C           C           1.5          0.2  Iris-setosa
4   5            C           B           1.4          0.2  Iris-setosa


Mengambil label Petal Length

In [263]:
# Ambil hanya kolom petal_length untuk clustering
X = data[['petal_length']].values

print("\nData IRIS Petal Length")
print(X)


Data IRIS Petal Length
[[1.4]
 [1.4]
 [1.3]
 [1.5]
 [1.4]
 [1.7]
 [1.4]
 [1.5]
 [1.4]
 [1.5]
 [1.5]
 [1.6]
 [1.4]
 [1.1]
 [1.2]
 [1.5]
 [1.3]
 [1.4]
 [1.7]
 [1.5]
 [1.7]
 [1.5]
 [1. ]
 [1.7]
 [1.9]
 [1.6]
 [1.6]
 [1.5]
 [1.4]
 [1.6]
 [1.6]
 [1.5]
 [1.5]
 [1.4]
 [1.5]
 [1.2]
 [1.3]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.6]
 [1.9]
 [1.4]
 [1.6]
 [1.4]
 [1.5]
 [1.4]
 [4.7]
 [4.5]
 [4.9]
 [4. ]
 [4.6]
 [4.5]
 [4.7]
 [3.3]
 [4.6]
 [3.9]
 [3.5]
 [4.2]
 [4. ]
 [4.7]
 [3.6]
 [4.4]
 [4.5]
 [4.1]
 [4.5]
 [3.9]
 [4.8]
 [4. ]
 [4.9]
 [4.7]
 [4.3]
 [4.4]
 [4.8]
 [5. ]
 [4.5]
 [3.5]
 [3.8]
 [3.7]
 [3.9]
 [5.1]
 [4.5]
 [4.5]
 [4.7]
 [4.4]
 [4.1]
 [4. ]
 [4.4]
 [4.6]
 [4. ]
 [3.3]
 [4.2]
 [4.2]
 [4.2]
 [4.3]
 [3. ]
 [4.1]
 [6. ]
 [5.1]
 [5.9]
 [5.6]
 [5.8]
 [6.6]
 [4.5]
 [6.3]
 [5.8]
 [6.1]
 [5.1]
 [5.3]
 [5.5]
 [5. ]
 [5.1]
 [5.3]
 [5.5]
 [6.7]
 [6.9]
 [5. ]
 [5.7]
 [4.9]
 [6.7]
 [4.9]
 [5.7]
 [6. ]
 [4.8]
 [4.9]
 [5.6]
 [5.8]
 [6.1]
 [6.4]
 [5.6]
 [5.1]
 [5.6]
 [6.1]
 [5.6]
 [5.5]
 [4.8]
 [5

 Melakukan Normalisasi Data

In [264]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Petal Length")
print(X_scaled)


Normalisasi data Petal Length
[[-1.3412724 ]
 [-1.3412724 ]
 [-1.39813811]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.17067529]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.2844067 ]
 [-1.227541  ]
 [-1.3412724 ]
 [-1.51186952]
 [-1.45500381]
 [-1.2844067 ]
 [-1.39813811]
 [-1.3412724 ]
 [-1.17067529]
 [-1.2844067 ]
 [-1.17067529]
 [-1.2844067 ]
 [-1.56873522]
 [-1.17067529]
 [-1.05694388]
 [-1.227541  ]
 [-1.227541  ]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.227541  ]
 [-1.227541  ]
 [-1.2844067 ]
 [-1.2844067 ]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.45500381]
 [-1.39813811]
 [-1.2844067 ]
 [-1.39813811]
 [-1.2844067 ]
 [-1.39813811]
 [-1.39813811]
 [-1.39813811]
 [-1.227541  ]
 [-1.05694388]
 [-1.3412724 ]
 [-1.227541  ]
 [-1.3412724 ]
 [-1.2844067 ]
 [-1.3412724 ]
 [ 0.53529583]
 [ 0.42156442]
 [ 0.64902723]
 [ 0.1372359 ]
 [ 0.47843012]
 [ 0.42156442]
 [ 0.53529583]
 [-0.26082403]
 [ 0.47843012]
 [ 0.08037019]
 [-0.14709262]
 [ 0.25096731]
 [ 0.1372359 ]
 [ 0.53529583]
 [-0.0902

Melakukan Clustering dengan 4 Cluster

In [265]:
# Clustering
kms = KMeans(n_clusters=4, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 0 2 2 2 0 2 0 0 0 0 2 0 2 2 0 2 0 2 0 2 2
 0 2 2 2 2 0 0 0 0 2 2 2 2 2 0 0 2 2 0 0 0 0 0 0 0 0 3 2 3 3 3 3 2 3 3 3 2
 2 3 2 2 2 3 3 3 2 3 2 3 2 3 3 2 2 3 3 3 3 3 2 3 3 3 3 2 3 3 2 2 3 3 2 2 2
 3 2]


Mengubah Label Cluster menjadi angka

In [266]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'C' 'C' 'C' 'A'
 'C' 'C' 'C' 'A' 'C' 'A' 'A' 'A' 'A' 'C' 'A' 'C' 'C' 'A' 'C' 'A' 'C' 'A'
 'C' 'C' 'A' 'C' 'C' 'C' 'C' 'A' 'A' 'A' 'A' 'C' 'C' 'C' 'C' 'C' 'A' 'A'
 'C' 'C' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'D' 'C' 'D' 'D' 'D' 'D' 'C' 'D'
 'D' 'D' 'C' 'C' 'D' 'C' 'C' 'C' 'D' 'D' 'D' 'C' 'D' 'C' 'D' 'C' 'D' 'D'
 'C' 'C' 'D' 'D' 'D' 'D' 'D' 'C' 'D' 'D' 'D' 'D' 'C' 'D' 'D' 'C' 'C' 'D'
 'D' 'C' 'C' 'C' 'D' 'C']


Mengubah Data Petal Length menjadi Cluster yang telah dilakukan sebelumnya dan disimpan ke CSV

In [267]:
# Ganti kolom petal_length dengan label huruf cluster
data['petal_length'] = cluster_labels_named_np
print("\nData IRIS dengan 'petal_length' diganti huruf cluster:")
print(data)

# Simpan ke CSV
data.to_csv("IRIS_Diskritisasi.csv", index=False)


Data IRIS dengan 'petal_length' diganti huruf cluster:
      id sepal_length sepal_width petal_length  petal_width           class
0      1            C           B            B          0.2     Iris-setosa
1      2            C           C            B          0.2     Iris-setosa
2      3            C           C            B          0.2     Iris-setosa
3      4            C           C            B          0.2     Iris-setosa
4      5            C           B            B          0.2     Iris-setosa
..   ...          ...         ...          ...          ...             ...
145  146            D           C            C          2.3  Iris-virginica
146  147            D           A            C          1.9  Iris-virginica
147  148            D           C            C          2.0  Iris-virginica
148  149            D           B            D          2.3  Iris-virginica
149  150            A           C            C          1.8  Iris-virginica

[150 rows x 6 columns]


### Mengganti Label Petal Width menjadi Kategori dengan 3 Cluster

 Mengambil Data IRIS

In [268]:
# Baca data
data = pd.read_csv("IRIS_Diskritisasi.csv")

print("Data IRIS")
print(data.head())

Data IRIS
   id sepal_length sepal_width petal_length  petal_width        class
0   1            C           B            B          0.2  Iris-setosa
1   2            C           C            B          0.2  Iris-setosa
2   3            C           C            B          0.2  Iris-setosa
3   4            C           C            B          0.2  Iris-setosa
4   5            C           B            B          0.2  Iris-setosa


 Mengambil label Petal Width

In [269]:
# Ambil hanya kolom petal_width untuk clustering
X = data[['petal_width']].values

print("\nData IRIS Petal Width")
print(X)


Data IRIS Petal Width
[[0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.1]
 [0.1]
 [0.2]
 [0.4]
 [0.4]
 [0.3]
 [0.3]
 [0.3]
 [0.2]
 [0.4]
 [0.2]
 [0.5]
 [0.2]
 [0.2]
 [0.4]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [0.4]
 [0.1]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.1]
 [0.2]
 [0.2]
 [0.3]
 [0.3]
 [0.2]
 [0.6]
 [0.4]
 [0.3]
 [0.2]
 [0.2]
 [0.2]
 [0.2]
 [1.4]
 [1.5]
 [1.5]
 [1.3]
 [1.5]
 [1.3]
 [1.6]
 [1. ]
 [1.3]
 [1.4]
 [1. ]
 [1.5]
 [1. ]
 [1.4]
 [1.3]
 [1.4]
 [1.5]
 [1. ]
 [1.5]
 [1.1]
 [1.8]
 [1.3]
 [1.5]
 [1.2]
 [1.3]
 [1.4]
 [1.4]
 [1.7]
 [1.5]
 [1. ]
 [1.1]
 [1. ]
 [1.2]
 [1.6]
 [1.5]
 [1.6]
 [1.5]
 [1.3]
 [1.3]
 [1.3]
 [1.2]
 [1.4]
 [1.2]
 [1. ]
 [1.3]
 [1.2]
 [1.3]
 [1.3]
 [1.1]
 [1.3]
 [2.5]
 [1.9]
 [2.1]
 [1.8]
 [2.2]
 [2.1]
 [1.7]
 [1.8]
 [1.8]
 [2.5]
 [2. ]
 [1.9]
 [2.1]
 [2. ]
 [2.4]
 [2.3]
 [1.8]
 [2.2]
 [2.3]
 [1.5]
 [2.3]
 [2. ]
 [2. ]
 [1.8]
 [2.1]
 [1.8]
 [1.8]
 [1.8]
 [2.1]
 [1.6]
 [1.9]
 [2. ]
 [2.2]
 [1.5]
 [1.4]
 [2.3]
 [2.4]
 [1.8]
 [1.8]
 [2.

 Melakukan Normalisasi Data

In [270]:
# Normalisasi
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
print("\nNormalisasi data Petal Width")
print(X_scaled)


Normalisasi data Petal Width
[[-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.05003079]
 [-1.18150376]
 [-1.31297673]
 [-1.31297673]
 [-1.4444497 ]
 [-1.31297673]
 [-1.31297673]
 [-1.4444497 ]
 [-1.4444497 ]
 [-1.31297673]
 [-1.05003079]
 [-1.05003079]
 [-1.18150376]
 [-1.18150376]
 [-1.18150376]
 [-1.31297673]
 [-1.05003079]
 [-1.31297673]
 [-0.91855782]
 [-1.31297673]
 [-1.31297673]
 [-1.05003079]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.05003079]
 [-1.4444497 ]
 [-1.31297673]
 [-1.4444497 ]
 [-1.31297673]
 [-1.31297673]
 [-1.4444497 ]
 [-1.31297673]
 [-1.31297673]
 [-1.18150376]
 [-1.18150376]
 [-1.31297673]
 [-0.78708485]
 [-1.05003079]
 [-1.18150376]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [-1.31297673]
 [ 0.26469891]
 [ 0.39617188]
 [ 0.39617188]
 [ 0.13322594]
 [ 0.39617188]
 [ 0.13322594]
 [ 0.52764485]
 [-0.26119297]
 [ 0.13322594]
 [ 0.26469891]
 [-0.26119297]
 [ 0.39617188]
 [-0.26119297]
 [ 0.26469891]
 [ 0.13322

 Melakukan Clustering dengan 3 Cluster

In [271]:
# Clustering
kms = KMeans(n_clusters=3, random_state=0, n_init="auto").fit(X_scaled)
print("\nHasil label cluster (dengan angka):")
print(kms.labels_)


Hasil label cluster (dengan angka):
[2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 0 1 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1]


 Mengubah Label Cluster menjadi angka

In [272]:
# Mapping label angka → huruf
label_mapping = {0:'A', 1:'B', 2:'C', 3:'D'}
cluster_labels_named = [label_mapping[label] for label in kms.labels_]
cluster_labels_named_np = np.array(cluster_labels_named)

# Cetak hasil label dalam bentuk huruf
print("\nHasil label cluster (dengan nama):")
print(cluster_labels_named_np)


Hasil label cluster (dengan nama):
['C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C'
 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C'
 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'C' 'A' 'A' 'A' 'A'
 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'B' 'A'
 'A' 'A' 'A' 'A' 'A' 'B' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A'
 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'A' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'A' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'A' 'B' 'B' 'B' 'A' 'A' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B' 'B'
 'B' 'B' 'B' 'B' 'B' 'B']


 Mengubah Data Petal Width menjadi Cluster yang telah dilakukan sebelumnya dan disimpan ke CSV

In [273]:
# Ganti kolom petal_width dengan label huruf cluster
data['petal_width'] = cluster_labels_named_np
print("\nData IRIS dengan 'petal_width' diganti huruf cluster:")
print(data)

# Simpan ke CSV
data.to_csv("IRIS_Diskritisasi.csv", index=False)


Data IRIS dengan 'petal_width' diganti huruf cluster:
      id sepal_length sepal_width petal_length petal_width           class
0      1            C           B            B           C     Iris-setosa
1      2            C           C            B           C     Iris-setosa
2      3            C           C            B           C     Iris-setosa
3      4            C           C            B           C     Iris-setosa
4      5            C           B            B           C     Iris-setosa
..   ...          ...         ...          ...         ...             ...
145  146            D           C            C           B  Iris-virginica
146  147            D           A            C           B  Iris-virginica
147  148            D           C            C           B  Iris-virginica
148  149            D           B            D           B  Iris-virginica
149  150            A           C            C           B  Iris-virginica

[150 rows x 6 columns]


### Hasil Akhir data IRIS yang telah di Diskritisasi

 Dengan Class

In [274]:
# Baca data
data = pd.read_csv("IRIS_Diskritisasi.csv")

print("Data IRIS Diskritisasi")
print(data)

Data IRIS Diskritisasi
      id sepal_length sepal_width petal_length petal_width           class
0      1            C           B            B           C     Iris-setosa
1      2            C           C            B           C     Iris-setosa
2      3            C           C            B           C     Iris-setosa
3      4            C           C            B           C     Iris-setosa
4      5            C           B            B           C     Iris-setosa
..   ...          ...         ...          ...         ...             ...
145  146            D           C            C           B  Iris-virginica
146  147            D           A            C           B  Iris-virginica
147  148            D           C            C           B  Iris-virginica
148  149            D           B            D           B  Iris-virginica
149  150            A           C            C           B  Iris-virginica

[150 rows x 6 columns]


Tanpa Class

In [275]:
# Baca data
data = pd.read_csv("IRIS_Diskritisasi.csv")

data = data.drop(columns=['class'])

print("Data IRIS Diskritisasi")
print(data)

Data IRIS Diskritisasi
      id sepal_length sepal_width petal_length petal_width
0      1            C           B            B           C
1      2            C           C            B           C
2      3            C           C            B           C
3      4            C           C            B           C
4      5            C           B            B           C
..   ...          ...         ...          ...         ...
145  146            D           C            C           B
146  147            D           A            C           B
147  148            D           C            C           B
148  149            D           B            D           B
149  150            A           C            C           B

[150 rows x 5 columns]


## Melakukan Klasifikasi dengan model Naive Bayas menggunakan data yang sudah di Diskritisasi

### Implementasi Naive Bayes

 Import Library

In [276]:
# Import Library
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import CategoricalNB
from sklearn.preprocessing import OrdinalEncoder
from sklearn.metrics import confusion_matrix, accuracy_score

### Implementasi Menggunakan Outlier Removal (penghapusan manual berdasarkan sepal_width)

Mengambil data yang sudah di Diskritisasi

In [277]:
# 1. Baca data
dataset = pd.read_csv('IRIS_Diskritisasi.csv')
print("=== DATA AWAL SEBELUM HAPUS OUTLIER ===")
dataset

=== DATA AWAL SEBELUM HAPUS OUTLIER ===


id sepal_length sepal_width petal_length petal_width           class
0      1            C           B            B           C     Iris-setosa
1      2            C           C            B           C     Iris-setosa
2      3            C           C            B           C     Iris-setosa
3      4            C           C            B           C     Iris-setosa
4      5            C           B            B           C     Iris-setosa
..   ...          ...         ...          ...         ...             ...
145  146            D           C            C           B  Iris-virginica
146  147            D           A            C           B  Iris-virginica
147  148            D           C            C           B  Iris-virginica
148  149            D           B            D           B  Iris-virginica
149  150            A           C            C           B  Iris-virginica

[150 rows x 6 columns]

Menghapus data yang dianggap outlier (di sini: kategori 'A' pada sepal_width).

In [278]:
# Penghapusan outlier: buang baris dengan kategori ekstrem (misal: 'A' pada sepal_width)
dataset_outlier_removed = dataset[dataset['sepal_width'] != 'A']

print("Data Setelah Outlier Removal:")
dataset_outlier_removed

Data Setelah Outlier Removal:


id sepal_length sepal_width petal_length petal_width           class
0      1            C           B            B           C     Iris-setosa
1      2            C           C            B           C     Iris-setosa
2      3            C           C            B           C     Iris-setosa
3      4            C           C            B           C     Iris-setosa
4      5            C           B            B           C     Iris-setosa
..   ...          ...         ...          ...         ...             ...
144  145            D           C            D           B  Iris-virginica
145  146            D           C            C           B  Iris-virginica
147  148            D           C            C           B  Iris-virginica
148  149            D           B            D           B  Iris-virginica
149  150            A           C            C           B  Iris-virginica

[103 rows x 6 columns]

Memisahkan fitur dan label

In [279]:
# 2. Ambil fitur dan label
X = dataset_outlier_removed.iloc[:, 4:].values  # kolom fitur setelah kolom ke-4
y = dataset_outlier_removed['class'].values     # target klasifikasi


Mengubah data kategori menjadi angka agar bisa digunakan oleh model.

In [280]:
# 3. Encode fitur kategori (string -> angka)
encoder = OrdinalEncoder()
X_encoded = encoder.fit_transform(X)


Membagi data jadi data latih dan data uji.

In [281]:
# 4. Split data
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=43)


Membuat dan melatih model Naive Bayes khusus untuk data kategori.

In [282]:
# 5. Model Naive Bayes untuk data kategori
classifier = CategoricalNB()
classifier.fit(X_train, y_train)


CategoricalNB()

Melakukan prediksi terhadap data uji.

In [283]:
# 6. Prediksi
y_pred = classifier.predict(X_test)
y_pred


array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-versicolor',
       'Iris-versicolor', 'Iris-setosa', 'Iris-virginica', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-virginica',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-setosa'], dtype='<U15')

Mengukur akurasi dan menampilkan confusion matrix.

In [284]:
# 7. Evaluasi
print("\n[VERSI DENGAN OUTLIER REMOVAL (buang sepal_width=='A')]")
print("Accuracy:", accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)



[VERSI DENGAN OUTLIER REMOVAL (buang sepal_width=='A')]
Accuracy: 1.0
Confusion Matrix:
 [[12  0  0]
 [ 0  4  0]
 [ 0  0  5]]


Menampilkan hasil perbandingan antara nilai asli dan prediksi.

In [285]:
# 8. Tampilkan hasil prediksi
df = pd.DataFrame({
    'Nilai Asli': y_test,
    'Nilai Prediksi': y_pred
})
print("\nHasil prediksi:")
df


Hasil prediksi:


Nilai Asli   Nilai Prediksi
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2       Iris-setosa      Iris-setosa
3       Iris-setosa      Iris-setosa
4    Iris-virginica   Iris-virginica
5    Iris-virginica   Iris-virginica
6   Iris-versicolor  Iris-versicolor
7   Iris-versicolor  Iris-versicolor
8       Iris-setosa      Iris-setosa
9    Iris-virginica   Iris-virginica
10      Iris-setosa      Iris-setosa
11      Iris-setosa      Iris-setosa
12  Iris-versicolor  Iris-versicolor
13      Iris-setosa      Iris-setosa
14   Iris-virginica   Iris-virginica
15      Iris-setosa      Iris-setosa
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18   Iris-virginica   Iris-virginica
19  Iris-versicolor  Iris-versicolor
20      Iris-setosa      Iris-setosa

### Implementasi Tanpa Menggunakan Outlier

Mengambil data yang sudah di Diskritisasi

In [286]:
# 1. Baca data
dataset = pd.read_csv('IRIS_Diskritisasi.csv')
print("=== DATA AWAL TANPA OUTLIER ===")
dataset

=== DATA AWAL TANPA OUTLIER ===


id sepal_length sepal_width petal_length petal_width           class
0      1            C           B            B           C     Iris-setosa
1      2            C           C            B           C     Iris-setosa
2      3            C           C            B           C     Iris-setosa
3      4            C           C            B           C     Iris-setosa
4      5            C           B            B           C     Iris-setosa
..   ...          ...         ...          ...         ...             ...
145  146            D           C            C           B  Iris-virginica
146  147            D           A            C           B  Iris-virginica
147  148            D           C            C           B  Iris-virginica
148  149            D           B            D           B  Iris-virginica
149  150            A           C            C           B  Iris-virginica

[150 rows x 6 columns]

Memisahkan fitur dan label

In [287]:
# 2. Ambil fitur dan label
X = dataset.iloc[:, 4:].values  # kolom fitur setelah kolom ke-4
y = dataset['class'].values     # target klasifikasi

Mengubah data kategori menjadi angka agar bisa digunakan oleh model.

In [288]:
# 3. Encode fitur kategori (string -> angka)
encoder = OrdinalEncoder()
X_encoded = encoder.fit_transform(X)

Membagi data jadi data latih dan data uji.

In [289]:
# 4. Split data
X_train, X_test, y_train, y_test = train_test_split(X_encoded, y, test_size=0.2, random_state=43)


Membuat dan melatih model Naive Bayes khusus untuk data kategori.

In [290]:
# 5. Model Naive Bayes untuk data kategori
classifier = CategoricalNB()
classifier.fit(X_train, y_train)

CategoricalNB()

Melakukan prediksi terhadap data uji.

In [291]:
# 6. Prediksi
y_pred = classifier.predict(X_test)
y_pred

array(['Iris-setosa', 'Iris-setosa', 'Iris-virginica', 'Iris-versicolor',
       'Iris-virginica', 'Iris-setosa', 'Iris-virginica',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-virginica', 'Iris-virginica', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-virginica', 'Iris-virginica',
       'Iris-virginica', 'Iris-setosa', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa'], dtype='<U15')

Mengukur akurasi dan menampilkan confusion matrix.

In [292]:
# 7. Evaluasi
print("\n[VERSI TANPA OUTLIER]")
print("Accuracy:", accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)


[VERSI TANPA OUTLIER]
Accuracy: 1.0
Confusion Matrix:
 [[13  0  0]
 [ 0  8  0]
 [ 0  0  9]]


Menampilkan hasil perbandingan antara nilai asli dan prediksi.

In [293]:
# 8. Tampilkan hasil prediksi
df = pd.DataFrame({
    'Nilai Asli': y_test,
    'Nilai Prediksi': y_pred
})
print("\nHasil prediksi:")
df


Hasil prediksi:


Nilai Asli   Nilai Prediksi
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7   Iris-versicolor  Iris-versicolor
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11  Iris-versicolor  Iris-versicolor
12   Iris-virginica   Iris-virginica
13      Iris-setosa      Iris-setosa
14  Iris-versicolor  Iris-versicolor
15  Iris-versicolor  Iris-versicolor
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18   Iris-virginica   Iris-virginica
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21      Iris-setosa      Iris-setosa
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26      Iris-setosa      Iris-setosa
27  Iris-versicolor  Iris-versicolor
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa

## Melakukan Klasifikasi dengan model Naive Bayas menggunakan data yang belum di Diskritisasi

### Implementasi Dengan Outlier Removal

Import Library.

In [294]:
# Import Library
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import GaussianNB
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import confusion_matrix, accuracy_score


Mengambil data IRIS asli.

In [295]:
# 1. Baca data
datairis = pd.read_csv('iris_dataset.csv')
datairis

id  sepal_length  sepal_width  petal_length  petal_width           class
0      1           5.1          3.5           1.4          0.2     Iris-setosa
1      2           4.9          3.0           1.4          0.2     Iris-setosa
2      3           4.7          3.2           1.3          0.2     Iris-setosa
3      4           4.6          3.1           1.5          0.2     Iris-setosa
4      5           5.0          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
145  146           6.7          3.0           5.2          2.3  Iris-virginica
146  147           6.3          2.5           5.0          1.9  Iris-virginica
147  148           6.5          3.0           5.2          2.0  Iris-virginica
148  149           6.2          3.4           5.4          2.3  Iris-virginica
149  150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 6 columns]

Menghapus data ekstrem (outlier) pada kolom sepal_width menggunakan metode IQR.

In [296]:
# Outlier removal berdasarkan kolom numerik 'sepal_width' (IQR method)
Q1 = datairis['sepal_width'].quantile(0.25)
Q3 = datairis['sepal_width'].quantile(0.75)
IQR = Q3 - Q1
datairis = datairis[(datairis['sepal_width'] >= Q1 - 1.5 * IQR) & (datairis['sepal_width'] <= Q3 + 1.5 * IQR)]

print("Data Setelah Outlier Removal:")
datairis

Data Setelah Outlier Removal:


id  sepal_length  sepal_width  petal_length  petal_width           class
0      1           5.1          3.5           1.4          0.2     Iris-setosa
1      2           4.9          3.0           1.4          0.2     Iris-setosa
2      3           4.7          3.2           1.3          0.2     Iris-setosa
3      4           4.6          3.1           1.5          0.2     Iris-setosa
4      5           5.0          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
145  146           6.7          3.0           5.2          2.3  Iris-virginica
146  147           6.3          2.5           5.0          1.9  Iris-virginica
147  148           6.5          3.0           5.2          2.0  Iris-virginica
148  149           6.2          3.4           5.4          2.3  Iris-virginica
149  150           5.9          3.0           5.1          1.8  Iris-virginica

[146 rows x 6 columns]

Memisahkan Fitur dan Label

In [297]:
# 2. Ambil fitur dan label
X = datairis.iloc[:, 1:5].values
y = datairis['class'].values

Mengubah label kelas dari teks ke angka.

In [298]:
# 3. Encode label class
le = LabelEncoder()
y_encoded = le.fit_transform(y)

Pisah Dataset ke Data Latih dan Data Uji.

In [299]:
# 4. Split data
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=43)


Membuat dan melatih model Naive Bayes.

In [300]:
# 5. Model Naive Bayes Gaussian
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB()

Melakukan prediksi terhadap data uji.

In [301]:
# 6. Prediksi
y_pred = classifier.predict(X_test)
y_pred

array([0, 1, 2, 2, 2, 1, 2, 1, 2, 0, 1, 2, 0, 1, 2, 0, 0, 1, 1, 0, 0, 1,
       0, 2, 1, 0, 1, 2, 0, 0])

Mengukur akurasi dan membuat matriks kebingungan.

In [302]:
# 7. Evaluasi
print("\n[VERSI DENGAN OUTLIER REMOVAL]")
print("Accuracy:", accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)



[VERSI DENGAN OUTLIER REMOVAL]
Accuracy: 0.9666666666666667
Confusion Matrix:
 [[11  0  0]
 [ 0  9  0]
 [ 0  1  9]]


Menampilkan nilai asli dan prediksi dalam bentuk tabel.

In [303]:
# 8. Tampilkan hasil prediksi
df = pd.DataFrame({
    'Nilai Asli': le.inverse_transform(y_test),
    'Nilai Prediksi': le.inverse_transform(y_pred)
})
print("\nHasil prediksi:")
df


Hasil prediksi:


Nilai Asli   Nilai Prediksi
0       Iris-setosa      Iris-setosa
1   Iris-versicolor  Iris-versicolor
2    Iris-virginica   Iris-virginica
3    Iris-virginica   Iris-virginica
4    Iris-virginica   Iris-virginica
5   Iris-versicolor  Iris-versicolor
6    Iris-virginica   Iris-virginica
7   Iris-versicolor  Iris-versicolor
8    Iris-virginica   Iris-virginica
9       Iris-setosa      Iris-setosa
10  Iris-versicolor  Iris-versicolor
11   Iris-virginica   Iris-virginica
12      Iris-setosa      Iris-setosa
13  Iris-versicolor  Iris-versicolor
14   Iris-virginica   Iris-virginica
15      Iris-setosa      Iris-setosa
16      Iris-setosa      Iris-setosa
17  Iris-versicolor  Iris-versicolor
18  Iris-versicolor  Iris-versicolor
19      Iris-setosa      Iris-setosa
20      Iris-setosa      Iris-setosa
21  Iris-versicolor  Iris-versicolor
22      Iris-setosa      Iris-setosa
23   Iris-virginica   Iris-virginica
24   Iris-virginica  Iris-versicolor
25      Iris-setosa      Iris-setosa
26  Iris-versicolor  Iris-versicolor
27   Iris-virginica   Iris-virginica
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa

### Implementasi Tanpa Menggunakan Outlier

Mengambil data IRIS asli.

In [304]:
# 1. Baca data
datairis = pd.read_csv('iris_dataset.csv')
print("Data Awal:")
datairis

Data Awal:


id  sepal_length  sepal_width  petal_length  petal_width           class
0      1           5.1          3.5           1.4          0.2     Iris-setosa
1      2           4.9          3.0           1.4          0.2     Iris-setosa
2      3           4.7          3.2           1.3          0.2     Iris-setosa
3      4           4.6          3.1           1.5          0.2     Iris-setosa
4      5           5.0          3.6           1.4          0.2     Iris-setosa
..   ...           ...          ...           ...          ...             ...
145  146           6.7          3.0           5.2          2.3  Iris-virginica
146  147           6.3          2.5           5.0          1.9  Iris-virginica
147  148           6.5          3.0           5.2          2.0  Iris-virginica
148  149           6.2          3.4           5.4          2.3  Iris-virginica
149  150           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 6 columns]

Memisahkan fitur dan label.

In [305]:
# 2. Ambil fitur dan label
X = datairis.iloc[:, 1:5].values  # sepal_length, sepal_width, petal_length, petal_width
y = datairis['class'].values      # target klasifikasi


Mengubah label kelas dari teks ke angka.

In [306]:
# 3. Encode label class (string ke angka)
le = LabelEncoder()
y_encoded = le.fit_transform(y)


Membagi data menjadi data latih dan data uji.

In [307]:
# 4. Split data
X_train, X_test, y_train, y_test = train_test_split(X, y_encoded, test_size=0.2, random_state=43)


Membuat dan melatih model Naive Bayes.

In [308]:
# 5. Model Naive Bayes Gaussian (data numerik)
classifier = GaussianNB()
classifier.fit(X_train, y_train)


GaussianNB()

Melakukan prediksi terhadap data uji.

In [309]:
# 6. Prediksi
y_pred = classifier.predict(X_test)
y_pred

array([0, 0, 2, 1, 2, 0, 2, 1, 1, 1, 0, 1, 2, 0, 1, 1, 0, 0, 2, 2, 0, 0,
       0, 1, 2, 2, 0, 1, 0, 0])

Mengukur akurasi dan membuat matriks kebingungan.

In [310]:
# 7. Evaluasi
print("\n[VERSI TANPA OUTLIER]")
print("Accuracy:", accuracy_score(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)



[VERSI TANPA OUTLIER]
Accuracy: 0.9666666666666667
Confusion Matrix:
 [[13  0  0]
 [ 0  8  0]
 [ 0  1  8]]


Menampilkan nilai asli dan prediksi dalam bentuk tabel.

In [311]:
# 8. Tampilkan hasil prediksi
df = pd.DataFrame({
    'Nilai Asli': le.inverse_transform(y_test),
    'Nilai Prediksi': le.inverse_transform(y_pred)
})
print("\nHasil prediksi:")
df


Hasil prediksi:


Nilai Asli   Nilai Prediksi
0       Iris-setosa      Iris-setosa
1       Iris-setosa      Iris-setosa
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5       Iris-setosa      Iris-setosa
6    Iris-virginica   Iris-virginica
7   Iris-versicolor  Iris-versicolor
8   Iris-versicolor  Iris-versicolor
9   Iris-versicolor  Iris-versicolor
10      Iris-setosa      Iris-setosa
11  Iris-versicolor  Iris-versicolor
12   Iris-virginica   Iris-virginica
13      Iris-setosa      Iris-setosa
14  Iris-versicolor  Iris-versicolor
15  Iris-versicolor  Iris-versicolor
16      Iris-setosa      Iris-setosa
17      Iris-setosa      Iris-setosa
18   Iris-virginica   Iris-virginica
19   Iris-virginica   Iris-virginica
20      Iris-setosa      Iris-setosa
21      Iris-setosa      Iris-setosa
22      Iris-setosa      Iris-setosa
23   Iris-virginica  Iris-versicolor
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26      Iris-setosa      Iris-setosa
27  Iris-versicolor  Iris-versicolor
28      Iris-setosa      Iris-setosa
29      Iris-setosa      Iris-setosa